"""empty message

Revision ID: 00ca2afa5729
Revises: a80322adf5ec
Create Date: 2023-03-24 11:10:56.924937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ca2afa5729'
down_revision = 'a80322adf5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_authorId_fkey', type_='foreignkey')
        batch_op.drop_column('imageId')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.Text(), nullable=True))
        batch_op.drop_column('imageId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('social_media')
        batch_op.drop_column('notifications')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('projects_authorId_fkey', 'users', ['authorId'], ['id'])

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
